name: publish

on:
  push:
    branches: [ main ]

jobs:
  publish-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.email "mpippi@gmail.com"
          git config --global user.name "masci"
          git remote add upstream https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Build site
        uses: jakejarvis/hugo-build-action@master
        with:
          args: -t terminal

      - name: Push gh-pages branch
        run: |
          git add -A
          git commit -m"rebuilding site from ${{ github.sha }}"
          git push upstream `git subtree split --prefix=public --ignore-joins`:gh-pages --force
